"""
This type stub file was generated by pyright.
"""

import sys
from abc import ABC, abstractmethod
from typing import Any, ClassVar, Literal, NoReturn, TYPE_CHECKING, TypeAlias, Union, overload
from .types import HashlibHash, JWKDict
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve, EllipticCurvePrivateKey, EllipticCurvePublicKey
from cryptography.hazmat.primitives.asymmetric.ed448 import Ed448PrivateKey, Ed448PublicKey
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey, RSAPublicKey
from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes, PublicKeyTypes

if sys.version_info >= (3, 10):
    ...
else:
    ...
AllowedRSAKeys: TypeAlias = Union[RSAPrivateKey, RSAPublicKey]
AllowedECKeys: TypeAlias = Union[EllipticCurvePrivateKey, EllipticCurvePublicKey]
AllowedOKPKeys: TypeAlias = Union[Ed25519PrivateKey, Ed25519PublicKey, Ed448PrivateKey, Ed448PublicKey]
AllowedKeys: TypeAlias = Union[AllowedRSAKeys, AllowedECKeys, AllowedOKPKeys]
AllowedPrivateKeys: TypeAlias = Union[RSAPrivateKey, EllipticCurvePrivateKey, Ed25519PrivateKey, Ed448PrivateKey]
AllowedPublicKeys: TypeAlias = Union[RSAPublicKey, EllipticCurvePublicKey, Ed25519PublicKey, Ed448PublicKey]
if TYPE_CHECKING or bool(os.getenv("SPHINX_BUILD", "")):
    ...
has_crypto = ...
requires_cryptography = ...
def get_default_algorithms() -> dict[str, Algorithm]:
    """
    Returns the algorithms that are implemented by the library.
    """
    ...

class Algorithm(ABC):
    """
    The interface for an algorithm used to sign and verify tokens.
    """
    _crypto_key_types: tuple[type[AllowedKeys], ...] | None = ...
    def compute_hash_digest(self, bytestr: bytes) -> bytes:
        """
        Compute a hash digest using the specified algorithm's hash algorithm.

        If there is no hash algorithm, raises a NotImplementedError.
        """
        ...
    
    def check_crypto_key_type(self, key: PublicKeyTypes | PrivateKeyTypes) -> None:
        """Check that the key belongs to the right cryptographic family.

        Note that this method only works when ``cryptography`` is installed.

        :param key: Potentially a cryptography key
        :type key: :py:data:`PublicKeyTypes <cryptography.hazmat.primitives.asymmetric.types.PublicKeyTypes>` | :py:data:`PrivateKeyTypes <cryptography.hazmat.primitives.asymmetric.types.PrivateKeyTypes>`
        :raises ValueError: if ``cryptography`` is not installed, or this method is called by a non-cryptography algorithm
        :raises InvalidKeyError: if the key doesn't match the expected key classes
        """
        ...
    
    @abstractmethod
    def prepare_key(self, key: Any) -> Any:
        """
        Performs necessary validation and conversions on the key and returns
        the key value in the proper format for sign() and verify().
        """
        ...
    
    @abstractmethod
    def sign(self, msg: bytes, key: Any) -> bytes:
        """
        Returns a digital signature for the specified message
        using the specified key value.
        """
        ...
    
    @abstractmethod
    def verify(self, msg: bytes, key: Any, sig: bytes) -> bool:
        """
        Verifies that the specified digital signature is valid
        for the specified message and key values.
        """
        ...
    
    @overload
    @staticmethod
    @abstractmethod
    def to_jwk(key_obj: Any, as_dict: Literal[True]) -> JWKDict:
        ...
    
    @overload
    @staticmethod
    @abstractmethod
    def to_jwk(key_obj: Any, as_dict: Literal[False] = ...) -> str:
        ...
    
    @staticmethod
    @abstractmethod
    def to_jwk(key_obj: Any, as_dict: bool = ...) -> JWKDict | str:
        """
        Serializes a given key into a JWK
        """
        ...
    
    @staticmethod
    @abstractmethod
    def from_jwk(jwk: str | JWKDict) -> Any:
        """
        Deserializes a given key from JWK back into a key object
        """
        ...
    
    def check_key_length(self, key: Any) -> str | None:
        """
        Return a warning message if the key is below the minimum
        recommended length for this algorithm, or None if adequate.
        """
        ...
    


class NoneAlgorithm(Algorithm):
    """
    Placeholder for use when no signing or verification
    operations are required.
    """
    def prepare_key(self, key: str | None) -> None:
        ...
    
    def sign(self, msg: bytes, key: None) -> bytes:
        ...
    
    def verify(self, msg: bytes, key: None, sig: bytes) -> bool:
        ...
    
    @staticmethod
    def to_jwk(key_obj: Any, as_dict: bool = ...) -> NoReturn:
        ...
    
    @staticmethod
    def from_jwk(jwk: str | JWKDict) -> NoReturn:
        ...
    


class HMACAlgorithm(Algorithm):
    """
    Performs signing and verification operations using HMAC
    and the specified hash function.
    """
    SHA256: ClassVar[HashlibHash] = ...
    SHA384: ClassVar[HashlibHash] = ...
    SHA512: ClassVar[HashlibHash] = ...
    def __init__(self, hash_alg: HashlibHash) -> None:
        ...
    
    def prepare_key(self, key: str | bytes) -> bytes:
        ...
    
    @overload
    @staticmethod
    def to_jwk(key_obj: str | bytes, as_dict: Literal[True]) -> JWKDict:
        ...
    
    @overload
    @staticmethod
    def to_jwk(key_obj: str | bytes, as_dict: Literal[False] = ...) -> str:
        ...
    
    @staticmethod
    def to_jwk(key_obj: str | bytes, as_dict: bool = ...) -> JWKDict | str:
        ...
    
    @staticmethod
    def from_jwk(jwk: str | JWKDict) -> bytes:
        ...
    
    def check_key_length(self, key: bytes) -> str | None:
        ...
    
    def sign(self, msg: bytes, key: bytes) -> bytes:
        ...
    
    def verify(self, msg: bytes, key: bytes, sig: bytes) -> bool:
        ...
    


if has_crypto:
    class RSAAlgorithm(Algorithm):
        """
        Performs signing and verification operations using
        RSASSA-PKCS-v1_5 and the specified hash function.
        """
        SHA256: ClassVar[type[hashes.HashAlgorithm]] = ...
        SHA384: ClassVar[type[hashes.HashAlgorithm]] = ...
        SHA512: ClassVar[type[hashes.HashAlgorithm]] = ...
        _crypto_key_types = ...
        _MIN_KEY_SIZE: ClassVar[int] = ...
        def __init__(self, hash_alg: type[hashes.HashAlgorithm]) -> None:
            ...
        
        def check_key_length(self, key: AllowedRSAKeys) -> str | None:
            ...
        
        def prepare_key(self, key: AllowedRSAKeys | str | bytes) -> AllowedRSAKeys:
            ...
        
        @overload
        @staticmethod
        def to_jwk(key_obj: AllowedRSAKeys, as_dict: Literal[True]) -> JWKDict:
            ...
        
        @overload
        @staticmethod
        def to_jwk(key_obj: AllowedRSAKeys, as_dict: Literal[False] = ...) -> str:
            ...
        
        @staticmethod
        def to_jwk(key_obj: AllowedRSAKeys, as_dict: bool = ...) -> JWKDict | str:
            ...
        
        @staticmethod
        def from_jwk(jwk: str | JWKDict) -> AllowedRSAKeys:
            ...
        
        def sign(self, msg: bytes, key: RSAPrivateKey) -> bytes:
            ...
        
        def verify(self, msg: bytes, key: RSAPublicKey, sig: bytes) -> bool:
            ...
        
    
    
    class ECAlgorithm(Algorithm):
        """
        Performs signing and verification operations using
        ECDSA and the specified hash function
        """
        SHA256: ClassVar[type[hashes.HashAlgorithm]] = ...
        SHA384: ClassVar[type[hashes.HashAlgorithm]] = ...
        SHA512: ClassVar[type[hashes.HashAlgorithm]] = ...
        _crypto_key_types = ...
        def __init__(self, hash_alg: type[hashes.HashAlgorithm], expected_curve: type[EllipticCurve] | None = ...) -> None:
            ...
        
        def prepare_key(self, key: AllowedECKeys | str | bytes) -> AllowedECKeys:
            ...
        
        def sign(self, msg: bytes, key: EllipticCurvePrivateKey) -> bytes:
            ...
        
        def verify(self, msg: bytes, key: AllowedECKeys, sig: bytes) -> bool:
            ...
        
        @overload
        @staticmethod
        def to_jwk(key_obj: AllowedECKeys, as_dict: Literal[True]) -> JWKDict:
            ...
        
        @overload
        @staticmethod
        def to_jwk(key_obj: AllowedECKeys, as_dict: Literal[False] = ...) -> str:
            ...
        
        @staticmethod
        def to_jwk(key_obj: AllowedECKeys, as_dict: bool = ...) -> JWKDict | str:
            ...
        
        @staticmethod
        def from_jwk(jwk: str | JWKDict) -> AllowedECKeys:
            ...
        
    
    
    class RSAPSSAlgorithm(RSAAlgorithm):
        """
        Performs a signature using RSASSA-PSS with MGF1
        """
        def sign(self, msg: bytes, key: RSAPrivateKey) -> bytes:
            ...
        
        def verify(self, msg: bytes, key: RSAPublicKey, sig: bytes) -> bool:
            ...
        
    
    
    class OKPAlgorithm(Algorithm):
        """
        Performs signing and verification operations using EdDSA

        This class requires ``cryptography>=2.6`` to be installed.
        """
        _crypto_key_types = ...
        def __init__(self, **kwargs: Any) -> None:
            ...
        
        def prepare_key(self, key: AllowedOKPKeys | str | bytes) -> AllowedOKPKeys:
            ...
        
        def sign(self, msg: str | bytes, key: Ed25519PrivateKey | Ed448PrivateKey) -> bytes:
            """
            Sign a message ``msg`` using the EdDSA private key ``key``
            :param str|bytes msg: Message to sign
            :param Ed25519PrivateKey}Ed448PrivateKey key: A :class:`.Ed25519PrivateKey`
                or :class:`.Ed448PrivateKey` isinstance
            :return bytes signature: The signature, as bytes
            """
            ...
        
        def verify(self, msg: str | bytes, key: AllowedOKPKeys, sig: str | bytes) -> bool:
            """
            Verify a given ``msg`` against a signature ``sig`` using the EdDSA key ``key``

            :param str|bytes sig: EdDSA signature to check ``msg`` against
            :param str|bytes msg: Message to sign
            :param Ed25519PrivateKey|Ed25519PublicKey|Ed448PrivateKey|Ed448PublicKey key:
                A private or public EdDSA key instance
            :return bool verified: True if signature is valid, False if not.
            """
            ...
        
        @overload
        @staticmethod
        def to_jwk(key: AllowedOKPKeys, as_dict: Literal[True]) -> JWKDict:
            ...
        
        @overload
        @staticmethod
        def to_jwk(key: AllowedOKPKeys, as_dict: Literal[False] = ...) -> str:
            ...
        
        @staticmethod
        def to_jwk(key: AllowedOKPKeys, as_dict: bool = ...) -> JWKDict | str:
            ...
        
        @staticmethod
        def from_jwk(jwk: str | JWKDict) -> AllowedOKPKeys:
            ...
        
    
    
