"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from typing import Any
from .types import JWKDict

class PyJWK:
    def __init__(self, jwk_data: JWKDict, algorithm: str | None = ...) -> None:
        """A class that represents a `JSON Web Key <https://www.rfc-editor.org/rfc/rfc7517>`_.

        :param jwk_data: The decoded JWK data.
        :type jwk_data: dict[str, typing.Any]
        :param algorithm: The key algorithm. If not specified, the key's ``alg`` will be used.
        :type algorithm: str or None
        :raises InvalidKeyError: If the key type (``kty``) is not found or unsupported, or if the curve (``crv``) is not found or unsupported.
        :raises MissingCryptographyError: If the algorithm requires ``cryptography`` to be installed and it is not available.
        :raises PyJWKError: If unable to find an algorithm for the key.
        """
        ...
    
    @staticmethod
    def from_dict(obj: JWKDict, algorithm: str | None = ...) -> PyJWK:
        """Creates a :class:`PyJWK` object from a JSON-like dictionary.

        :param obj: The JWK data, as a dictionary
        :type obj: dict[str, typing.Any]
        :param algorithm: The key algorithm. If not specified, the key's ``alg`` will be used.
        :type algorithm: str or None
        :rtype: PyJWK
        """
        ...
    
    @staticmethod
    def from_json(data: str, algorithm: None = ...) -> PyJWK:
        """Create a :class:`PyJWK` object from a JSON string.
        Implicitly calls :meth:`PyJWK.from_dict()`.

        :param str data: The JWK data, as a JSON string.
        :param algorithm:  The key algorithm.  If not specific, the key's ``alg`` will be used.
        :type algorithm: str or None

        :rtype: PyJWK
        """
        ...
    
    @property
    def key_type(self) -> str | None:
        """The `kty` property from the JWK.

        :rtype: str or None
        """
        ...
    
    @property
    def key_id(self) -> str | None:
        """The `kid` property from the JWK.

        :rtype: str or None
        """
        ...
    
    @property
    def public_key_use(self) -> str | None:
        """The `use` property from the JWK.

        :rtype: str or None
        """
        ...
    


class PyJWKSet:
    def __init__(self, keys: list[JWKDict]) -> None:
        ...
    
    @staticmethod
    def from_dict(obj: dict[str, Any]) -> PyJWKSet:
        ...
    
    @staticmethod
    def from_json(data: str) -> PyJWKSet:
        ...
    
    def __getitem__(self, kid: str) -> PyJWK:
        ...
    
    def __iter__(self) -> Iterator[PyJWK]:
        ...
    


class PyJWTSetWithTimestamp:
    def __init__(self, jwk_set: PyJWKSet) -> None:
        ...
    
    def get_jwk_set(self) -> PyJWKSet:
        ...
    
    def get_timestamp(self) -> float:
        ...
    


