"""
This type stub file was generated by pyright.
"""

import json
from collections.abc import Sequence
from typing import Any, TYPE_CHECKING
from .algorithms import Algorithm, AllowedPrivateKeys, AllowedPublicKeys
from .api_jwk import PyJWK
from .types import SigOptions

if TYPE_CHECKING:
    ...
_ALGORITHM_UNSET = ...
class PyJWS:
    header_typ = ...
    def __init__(self, algorithms: Sequence[str] | None = ..., options: SigOptions | None = ...) -> None:
        ...
    
    def register_algorithm(self, alg_id: str, alg_obj: Algorithm) -> None:
        """
        Registers a new Algorithm for use when creating and verifying tokens.

        :param str alg_id: the ID of the Algorithm
        :param alg_obj: the Algorithm object
        :type alg_obj: Algorithm
        """
        ...
    
    def unregister_algorithm(self, alg_id: str) -> None:
        """
        Unregisters an Algorithm for use when creating and verifying tokens
        :param str alg_id: the ID of the Algorithm
        :raises KeyError: if algorithm is not registered.
        """
        ...
    
    def get_algorithms(self) -> list[str]:
        """
        Returns a list of supported values for the `alg` parameter.

        :rtype: list[str]
        """
        ...
    
    def get_algorithm_by_name(self, alg_name: str) -> Algorithm:
        """
        For a given string name, return the matching Algorithm object.

        Example usage:
        >>> jws_obj = PyJWS()
        >>> jws_obj.get_algorithm_by_name("RS256")

        :param alg_name: The name of the algorithm to retrieve
        :type alg_name: str
        :rtype: Algorithm
        """
        ...
    
    def encode(self, payload: bytes, key: AllowedPrivateKeys | PyJWK | str | bytes, algorithm: str | None = ..., headers: dict[str, Any] | None = ..., json_encoder: type[json.JSONEncoder] | None = ..., is_payload_detached: bool = ..., sort_headers: bool = ...) -> str:
        ...
    
    def decode_complete(self, jwt: str | bytes, key: AllowedPublicKeys | PyJWK | str | bytes = ..., algorithms: Sequence[str] | None = ..., options: SigOptions | None = ..., detached_payload: bytes | None = ..., **kwargs: dict[str, Any]) -> dict[str, Any]:
        ...
    
    def decode(self, jwt: str | bytes, key: AllowedPublicKeys | PyJWK | str | bytes = ..., algorithms: Sequence[str] | None = ..., options: SigOptions | None = ..., detached_payload: bytes | None = ..., **kwargs: dict[str, Any]) -> Any:
        ...
    
    def get_unverified_header(self, jwt: str | bytes) -> dict[str, Any]:
        """Returns back the JWT header parameters as a `dict`

        Note: The signature is not verified so the header parameters
        should not be fully trusted until signature verification is complete
        """
        ...
    
    _supported_crit: set[str] = ...


_jws_global_obj = ...
encode = ...
decode_complete = ...
decode = ...
register_algorithm = ...
unregister_algorithm = ...
get_algorithm_by_name = ...
get_unverified_header = ...
