"""
This type stub file was generated by pyright.
"""

cryptography_version = ...
def info() -> dict[str, dict[str, str]]:
    """
    Generate information for a bug report.
    Based on the requests package help utility module.
    """
    ...

def main() -> None:
    """Pretty-print the bug information as JSON."""
    ...

if __name__ == "__main__":
    ...
