"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .api_jwk import PyJWKSet

class JWKSetCache:
    def __init__(self, lifespan: float) -> None:
        ...
    
    def put(self, jwk_set: PyJWKSet) -> None:
        ...
    
    def get(self) -> Optional[PyJWKSet]:
        ...
    
    def is_expired(self) -> bool:
        ...
    


