// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/tasks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].put').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.bun/@nuxt+icon@1.15.0+1239c54f7b910dc5/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../packages/nuxt/src/runtime/server/api/_auth/session.get').default>>>>
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../packages/nuxt/src/runtime/server/api/_auth/session.delete').default>>>>
    }
    '/api/_auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../packages/nuxt/src/runtime/server/api/_auth/login.post').default>>>>
    }
    '/api/_auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../packages/nuxt/src/runtime/server/api/_auth/logout.post').default>>>>
    }
    '/api/_auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../packages/nuxt/src/runtime/server/api/_auth/refresh.post').default>>>>
    }
    '/api/_auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../packages/nuxt/src/runtime/server/api/_auth/register.post').default>>>>
    }
  }
}
export {}