/**
 * collect-docs.ts — Copies per-package docs into the root VitePress docs site.
 *
 * Run: bun scripts/collect-docs.ts
 *
 * For each package that has a docs/ directory, copies its contents into
 * docs/packages/<name>/ and generates a sidebar configuration file at
 * docs/.vitepress/sidebar-generated.ts.
 */

import { existsSync, mkdirSync, rmSync, readdirSync, statSync, copyFileSync, writeFileSync } from "fs";
import { join, relative, basename, dirname, extname } from "path";

const ROOT = join(import.meta.dir, "..");
const DOCS_OUT = join(ROOT, "docs", "packages");
const SIDEBAR_OUT = join(ROOT, "docs", ".vitepress", "sidebar-generated.ts");

interface PackageConfig {
  name: string;
  label: string;
  docsDir: string;
}

const packages: PackageConfig[] = [
  { name: "py", label: "Python", docsDir: "packages/py/docs" },
  { name: "ts", label: "TypeScript", docsDir: "packages/ts/docs" },
  { name: "node", label: "Node.js", docsDir: "packages/node/docs" },
  { name: "vue", label: "Vue", docsDir: "packages/vue/docs" },
  { name: "nuxt", label: "Nuxt", docsDir: "packages/nuxt/docs" },
  { name: "hono", label: "Hono", docsDir: "packages/hono/docs" },
  { name: "express", label: "Express", docsDir: "packages/express/docs" },
  { name: "fastify", label: "Fastify", docsDir: "packages/fastify/docs" },
  { name: "h3", label: "H3", docsDir: "packages/h3/docs" },
];

// ── Helpers ───────────────────────────────────────────────────────

function copyDirRecursive(src: string, dest: string): void {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

/** Title-case a filename: "getting-started.md" → "Getting Started" */
function titleFromFilename(filename: string): string {
  const name = basename(filename, extname(filename));
  if (name === "index") return "Overview";
  return name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

interface SidebarItem {
  text: string;
  link?: string;
  items?: SidebarItem[];
  collapsed?: boolean;
}

/** Walk a collected docs directory and produce a sidebar tree. */
function buildSidebar(dir: string, urlPrefix: string): SidebarItem[] {
  if (!existsSync(dir)) return [];

  const items: SidebarItem[] = [];
  const entries = readdirSync(dir).sort();

  // Separate files and directories
  const files: string[] = [];
  const dirs: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      dirs.push(entry);
    } else if (entry.endsWith(".md")) {
      files.push(entry);
    }
  }

  // index.md goes first as the section overview
  if (files.includes("index.md")) {
    items.push({
      text: "Overview",
      link: `${urlPrefix}/`,
    });
  }

  // Other markdown files
  for (const file of files) {
    if (file === "index.md") continue;
    const name = basename(file, ".md");
    items.push({
      text: titleFromFilename(file),
      link: `${urlPrefix}/${name}`,
    });
  }

  // Subdirectories
  for (const sub of dirs) {
    const subItems = buildSidebar(join(dir, sub), `${urlPrefix}/${sub}`);
    if (subItems.length > 0) {
      items.push({
        text: titleFromFilename(sub),
        collapsed: true,
        items: subItems,
      });
    }
  }

  return items;
}

// ── Main ──────────────────────────────────────────────────────────

console.log("Collecting docs from packages...");

// Clean output directory
if (existsSync(DOCS_OUT)) {
  rmSync(DOCS_OUT, { recursive: true });
}
mkdirSync(DOCS_OUT, { recursive: true });

const sidebarSections: Record<string, SidebarItem[]> = {};

for (const pkg of packages) {
  const srcDir = join(ROOT, pkg.docsDir);
  if (!existsSync(srcDir)) {
    console.log(`  [skip] ${pkg.name} — no docs/ directory`);
    continue;
  }

  const destDir = join(DOCS_OUT, pkg.name);
  copyDirRecursive(srcDir, destDir);
  console.log(`  [copy] ${pkg.name} → docs/packages/${pkg.name}/`);

  const sidebar = buildSidebar(destDir, `/packages/${pkg.name}`);
  if (sidebar.length > 0) {
    sidebarSections[pkg.name] = sidebar;
  }
}

// Generate sidebar config
const sidebarEntries: string[] = [];
for (const pkg of packages) {
  if (!sidebarSections[pkg.name]) continue;
  sidebarEntries.push(
    `  "/packages/${pkg.name}/": [\n    {\n      text: "${pkg.label}",\n      items: ${JSON.stringify(sidebarSections[pkg.name], null, 8).split("\n").join("\n    ")}\n    }\n  ]`,
  );
}

const sidebarTs = `// Auto-generated by scripts/collect-docs.ts — do not edit manually.
import type { DefaultTheme } from "vitepress";

export const packageSidebars: Record<string, DefaultTheme.SidebarItem[]> = {
${sidebarEntries.join(",\n")}
};
`;

writeFileSync(SIDEBAR_OUT, sidebarTs);
console.log(`  [write] docs/.vitepress/sidebar-generated.ts`);
console.log("Done.");
